# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Prashanth Prakash
title: Researcher
email: prashanth.rp94@gmail.com
#website: www.github.com/sproogen/resume-theme======

# Social links
#twitter_username: facespics
github_username:  prashanth-prakash
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: prashanthrp
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Prashanth and I'm a reseaerch technologist at Northwestern University. As part of my research I have worked on signal processing and machine learning algorithms for brain computer interfaces and neuroscience. My interests have been in learning representations in the brain and building decoders that help in translating neural signals to behavior. In addition to my interest in neuroscience, I am always on the lookout for new and interesting projects to work on. I have worked on many machine learning projects in other fields as well. I am currently intersted in exploring machine learning tools used on healthcare data and am open to collaborating on projects, feel free to contact me via email or linkedin. 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Publications
more_content: | # this will include new lines to allow paragraphs
  - Purushothaman G, Prakash PR, Kothari S (2018) Investigation of multiple frequency recognition from single-channel steady-state visual evoked potential for efficient brain–computer interfaces application. IET signal processing journal [Available here](https://ieeexplore.ieee.org/document/8352530)
  - Lansdell, B.J., Prakash, P.R., and Kording, K.P. (2019). Learning to solve the credit assignment problem. Presented at Neural Information processing Systems 2019. [Available here](https://arxiv.org/pdf/1906.00889.pdf) 
more_title: Skills 
more_content: |
  - Programming languages: Python,SQL, MATLAB, C++
  - Tools: Numpy, NLTK, Tensorflow, Keras, Pandas, sklearn, scipy
  - Technical: Machine learning, Deep learning, Data cleaning, Data Analysis
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
